### ISSUE TITLE
Support for multiple paths

### ISSUE THREAD

**Issue by brettwinters** [visionwx/ali-cdn-refresh#1]
I have a wildcard domain (and I think it's not supported on aliyun) so would you be able to support multiple paths, like this

```yaml
- name: CDN Refresh
    uses: visionwx/ali-cdn-refresh@v1.0.0
    with:
        accessKeyId: ${{ secrets.ALIYUN_CDN_ACCESS_KEY_ID }}
        accessKeySecret: ${{ secrets.ALIYUN_CDN_ACCESS_KEY_SECRET }}
        type: Directory
        path: |
            https://subdomain1.domain.com/
            https://subdomain2.domain.com/
            https://subdomain3.domain.com/
            https://subdomain4.domain.com/
```
